4.1. Added video-preview after 1 sec over movie-card.
htmlacademy-react/1329715-what-to-watch-6 pull request #6
Opened 2021-02-19 10:47 UTC by rmk1409

2021-02-23 20:42 UTC, at31oldfox requested changes

2021-02-23 20:42 UTC, at31oldfox commented on src/components/video-player/video-player.jsx
> +  const {film, videoRef} = props;
можно сразу ```const VideoPlayer = ({film, videoRef}) => { ``` если props не много

2021-02-23 20:42 UTC, at31oldfox commented on src/components/video-player/video-player.jsx
> +  return <>
и тогда можно убрать ```return ```

2021-02-23 20:42 UTC, at31oldfox commented on src/components/film-details/film-details.jsx
> +    <React.Fragment key={index}>{value}{index < (film.starring.length - 1) ? <br/> : ``}</React.Fragment>
лучше использовать что-то одно ```<></>``` или ```<React.Fragment></React.Fragment>``` это по сути одно и тоже, но читается лучше если все одинаковое.

2021-02-23 20:42 UTC, at31oldfox commented on src/components/film-reviews/film-reviews.jsx
> +  reviews = reviews.filter((review) => review[`film_id`] === film.id);
переопределять пропс очень плохая идея, ведет к непредсказуемым результатам,  ничего не мешает нам завести еще одну переменную.

2021-02-23 20:42 UTC, at31oldfox commented on src/components/film/film.jsx
>    const id = +useParams().id;
редкая форма записи))

2021-02-23 20:42 UTC, at31oldfox commented on src/components/review/review.jsx
> +  const dayjs = require(`dayjs`);
зачем?

2021-02-23 20:42 UTC, at31oldfox commented on src/components/review/review.jsx
> +  const dayjs = require(`dayjs`);
и зачем это здесь?

2021-02-24 06:59 UTC, rmk1409 commented on src/components/film-details/film-details.jsx
> +    <React.Fragment key={index}>{value}{index < (film.starring.length - 1) ? <br/> : ``}</React.Fragment>
Да, я тоже полностью за 1 стиль и пробовал без React.Fragment. Если здесь заменить на <>, то как минимум EsLint начинает ругаться.

2021-02-24 06:59 UTC, rmk1409 commented on src/components/video-player/video-player.jsx
> +  const {film, videoRef} = props;
fixed.

2021-02-24 06:59 UTC, rmk1409 commented on src/components/video-player/video-player.jsx
> +  return <>
fixed.

2021-02-24 07:00 UTC, rmk1409 commented on src/components/film-reviews/film-reviews.jsx
> +  reviews = reviews.filter((review) => review[`film_id`] === film.id);
fixed.

2021-02-24 07:12 UTC, rmk1409 commented on src/components/film/film.jsx
>    const id = +useParams().id;
А как по другому это можно сделать? Документация Реакта предлагает вытаскивать параметры запроса через useParams(), ещё нашёл вариант с this.props.match.params, но в пропсах нет поля match.

2021-02-24 07:24 UTC, rmk1409 commented on src/components/review/review.jsx
> +  const dayjs = require(`dayjs`);
Для вывода даты в нужном формате, в js же нет лёгкого пути для форматы даты, если пользоваться только Date, то придётся заводить словарь месяцев, в много где добавлять +1, иначе как отформотировать, чтобы было минимум кода и нужный формат?

2021-02-25 22:14 UTC, at31oldfox commented on src/components/film-details/film-details.jsx
> +    <React.Fragment key={index}>{value}{index < (film.starring.length - 1) ? <br/> : ``}</React.Fragment>
оставить что-то одно )

2021-02-25 22:18 UTC, at31oldfox commented on src/components/film/film.jsx
>    const id = +useParams().id;
Приемлемая запись, просто редкая. Минусы - если не будет id то будет ошибка, неявное приведение через `+` иногда ограничивают на уровне линтера, потому что это может быть источником опечаток. 
Обычно `const {id} = useParams()`.

2021-02-25 22:18 UTC, at31oldfox commented on src/components/film/film.jsx
>    const id = +useParams().id;
Исправлять на усмотрение.

2021-02-25 22:20 UTC, at31oldfox commented on src/components/review/review.jsx
> +  const dayjs = require(`dayjs`);
вопрос про `requre`  и про его место положение, в проекте мы принимаем что все импорты в самом верху и через import es6

2021-02-25 22:20 UTC, at31oldfox commented
Оставил комменты, остальное ок.

2021-02-26 02:23 UTC, rmk1409 commented on src/components/film-details/film-details.jsx
> +    <React.Fragment key={index}>{value}{index < (film.starring.length - 1) ? <br/> : ``}</React.Fragment>
![image](https://user-images.githubusercontent.com/7755430/109246029-91fd0000-77f2-11eb-9470-33ed95738da2.png)

Как удалить в этом месте React.Fragment, когда он ругается?

2021-02-26 02:26 UTC, rmk1409 commented on src/components/film/film.jsx
>    const id = +useParams().id;
fixed.

2021-02-26 02:31 UTC, rmk1409 commented on src/components/review/review.jsx
> +  const dayjs = require(`dayjs`);
fixed.

2021-02-26 02:33 UTC, rmk1409 commented on src/components/film-details/film-details.jsx
> +    <React.Fragment key={index}>{value}{index < (film.starring.length - 1) ? <br/> : ``}</React.Fragment>
Хотя не, можно без ключа. 
![image](https://user-images.githubusercontent.com/7755430/109246920-20be4c80-77f4-11eb-8197-205df1d4d90d.png)

2021-02-26 02:33 UTC, rmk1409 commented on src/components/film-details/film-details.jsx
> +    <React.Fragment key={index}>{value}{index < (film.starring.length - 1) ? <br/> : ``}</React.Fragment>
fixed.

2021-02-26 06:22 UTC, at31oldfox commented on src/components/film-details/film-details.jsx
> +    <>
цели не стоит удалить именно React.Fragment, цель была прийти к чему-то одному.

2021-02-26 06:22 UTC, merged